# Generated by Django 4.2.7 on 2023-12-15 14:37

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('movies', '0002_alter_movie_actors_alter_movie_genre_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reviw',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stars', models.IntegerField(validators=[django.core.validators.MinValueValidator(1, 'Avaliação Mínima é 1 Estrela'), django.core.validators.MaxValueValidator(5, 'Avaliação Máxima é 5 Estrelas')])),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Cometário')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='movies.movie', verbose_name='Filme')),
            ],
        ),
    ]
