# Generated by Django 4.2.7 on 2023-12-15 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_remove_movie_imdb_rating'),
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Reviw',
            new_name='Review',
        ),
    ]
