# Generated by Django 4.2.7 on 2023-12-15 14:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_rename_reviw_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='stars',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0, 'Avaliação Mínima é 0 Estrela'), django.core.validators.MaxValueValidator(5, 'Avaliação Máxima é 5 Estrelas')]),
        ),
    ]
