# Generated by Django 4.2.7 on 2023-12-15 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='birthday',
            field=models.DateField(blank=True, null=True, verbose_name='Data de nascimento'),
        ),
        migrations.AlterField(
            model_name='actor',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='actor',
            name='nationality',
            field=models.CharField(choices=[('USA', 'Estados Unidos'), ('BRA', 'Brasil')], max_length=100, verbose_name='Nacionalidade'),
        ),
    ]
